[phases.setup]
aptPkgs = [
  "xvfb",
  "chromium",
  "chromium-driver",
  "fonts-liberation",
  "fonts-noto",
  "libasound2",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libxss1",
  "libxtst6",
  "ca-certificates",
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
